# Generated by Django 5.2.8 on 2025-11-11 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Suministro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Tornillos M8, Aceite Motor, Filtro Aire', max_length=100, verbose_name='Nombre del suministro')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción detallada')),
                ('stock', models.PositiveIntegerField(default=0, help_text='Cantidad disponible en inventario', verbose_name='Cantidad en stock')),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, help_text='Precio por unidad en moneda local', max_digits=10, verbose_name='Precio unitario')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de última actualización')),
            ],
            options={
                'verbose_name': 'Suministro',
                'verbose_name_plural': 'Suministros',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='OrdenDeTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Breve descripción del problema', max_length=200, verbose_name='Título de la orden')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('descripcion_falla', models.TextField(help_text='Describa en detalle la falla o problema (mínimo 20 caracteres)', verbose_name='Descripción de la falla')),
                ('prioridad', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], default='Media', max_length=10, verbose_name='Nivel de prioridad')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Progreso', 'En Progreso'), ('Cerrada', 'Cerrada')], default='Pendiente', max_length=15, verbose_name='Estado actual')),
                ('fecha_cierre_real', models.DateTimeField(blank=True, null=True, verbose_name='Fecha real de cierre')),
                ('operario_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Operario asignado')),
                ('operario_creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Operario que reporta')),
            ],
            options={
                'verbose_name': 'Orden de Trabajo',
                'verbose_name_plural': 'Órdenes de Trabajo',
                'ordering': ['-fecha_creacion'],
                'permissions': [('can_close_order', 'Puede cerrar órdenes de trabajo')],
            },
        ),
        migrations.CreateModel(
            name='ConsumoSuministro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_usada', models.PositiveIntegerField(help_text='Cantidad consumida del suministro', verbose_name='Cantidad utilizada')),
                ('fecha_consumo', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del consumo')),
                ('operario_registra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Operario que registra')),
                ('orden_de_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='gestion_mantenimiento.ordendetrabajo', verbose_name='Orden de trabajo asociada')),
                ('suministro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='gestion_mantenimiento.suministro', verbose_name='Suministro utilizado')),
            ],
            options={
                'verbose_name': 'Consumo de Suministro',
                'verbose_name_plural': 'Consumos de Suministros',
                'ordering': ['-fecha_consumo'],
                'unique_together': {('orden_de_trabajo', 'suministro')},
            },
        ),
    ]
