# Generated by Django 5.2.8 on 2025-11-11 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_mantenimiento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumosuministro',
            name='operario_registra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Operario que registra'),
        ),
    ]
