# Generated by Django 5.2.8 on 2025-11-13 19:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_mantenimiento', '0002_alter_consumosuministro_operario_registra'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendetrabajo',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, help_text='Fecha en que se reporta la falla', verbose_name='Fecha de reporte'),
        ),
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación en sistema'),
        ),
    ]
